export const turnos = [
  {
    id: "2",
    title: "Manhã",
    color: "#d9534f",
    inicio: "07:00",
    fim: "13:00",
    vagas: 3,
    sequencia: 1,
    domingo: true,
    segunda: true,
    terca: true,
    quarta: true,
    quinta: true,
    sexta: true,
    sabado: true,
  },
  {
    id: "1",
    title: "Tarde",
    color: "#f0ad4e",
    inicio: "13:00",
    fim: "19:00",
    vagas: 2,
    sequencia: 1,
    domingo: true,
    segunda: true,
    terca: true,
    quarta: true,
    quinta: true,
    sexta: true,
    sabado: true,
  },
  {
    id: "3",
    title: "Noite",
    color: "#5bc0de",
    inicio: "19:00",
    fim: "01:00",
    vagas: 1,
    sequencia: 3,
    domingo: true,
    segunda: true,
    terca: true,
    quarta: true,
    quinta: true,
    sexta: false,
    sabado: true,
  },
  // Add other shifts as needed
];
