export const styles = {
  headerTableCell: {
    border: "1px solid #ccc",
    padding: 2,
    backgroundColor: "#f9f9f9",
    textAlign: "center",
    fontWeight: "bold",
  },
  weekdayTableCell: {
    border: "1px solid #ccc",
    padding: 2,
    backgroundColor: "#f0f0f0",
    textAlign: "center",
    fontWeight: "bold",
  },
  turnoTableCell: {
    border: "1px solid #ccc",
    padding: 2,
    backgroundColor: "#f9f9f9",
    textAlign: "center",
    fontWeight: "bold",
  },
  timeTableCell: {
    padding: 0,
    fontSize: 12,
    color: "#777",
    fontWeight: "normal",
  },
  areaTableCell: {
    border: "1px solid #ccc",
    padding: 0,
    minWidth: "150px",
  },
  indisponivelBox: {
    color: "#aaa",
    pointerEvents: "none",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  overlayBox: {
    padding: 2,
    width: "200px",
    backgroundColor: "white",
    border: "1px solid #ccc",
    boxShadow: "0px 4px 12px rgba(0,0,0,0.2)",
    alignItems: "center",
    justifyContent: "center",
    display: "flex",
    borderRadius: "5px",
  },
};
